apiVersion: v1
kind: Service
metadata:
  name: peta-application-service
spec:
  selector:
    app: peta-application
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer